spring.application.name=user-service
server.port=8085
server.shutdown=graceful

######## Spring Actuator Config ######################
management.endpoints.web.exposure.include=*
management.info.git.mode=full

##Security note
##Exposing * is fine for development. In production, you'd typically restrict it:
##management.endpoints.web.exposure.include=health,info,metrics,prometheus

###################### Database Configuration ########################
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:55432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

###################### JWT Configuration ########################
jwt.secret=${JWT_SECRET:my-super-secret-key-for-jwt-token-that-should-be-very-long}
jwt.expiration-ms=86400000


